version: '3'

services:
  recipe-search:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recipe-search
    restart: unless-stopped
    env_file: .env
    environment:
      - APP_PORT=$APP_PORT
      - GIPHY_API_KEY=$GIPHY_API_KEY
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - .:/usr/src/app
    command: yarn dev